const definitions = {
    "modèle" : "Un modèle est, en économie, une représentation simplifiée de la réalité économique ou d'une partie de celle-ci. Un modèle économique se base sur des hypothèses économiques et a recours au langage mathématique.",
    "soutenabilité" : "Il désigne ce qui paraît raisonnablement contrôlable et le mode d'organisation à mettre en place en vue d'assurer la pérennité de la société humaine",
    "marché": "Le marché comme mécanisme de coordination est un lieu physique ou abstrait de rencontre entre offreurs et demandeurs d'un bien ou d'un service.",
    "inflation": "L'inflation est l'augmentation générale et continue des prix des biens et services dans une économie, réduisant ainsi le pouvoir d'achat.",
    "crédit": "Le crédit est un prêt accordé par une institution financière ou un prêteur à un emprunteur, qui s'engage à rembourser avec des intérêts selon des conditions fixées.",
    "action": "Une action est une part de propriété dans une entreprise, qui donne à son détenteur un droit sur une partie des bénéfices (dividendes) et éventuellement un droit de vote lors des assemblées générales.",
    "libéral": "Un libéral, en économie, est une personne qui prône la liberté des marchés, une intervention limitée de l'État et la libre concurrence pour favoriser la croissance et l'efficacité économique.",
    "deflation": "La déflation est une baisse généralisée et prolongée des prix des biens et services, souvent liée à une contraction de la demande, qui peut entraîner une récession économique.",
    "krach": "Un krach est une chute brutale et soudaine des prix sur un marché financier, souvent causée par une panique des investisseurs, et pouvant entraîner une crise économique.",
    "allocations": "Les allocations sont des sommes d'argent versées par l'État ou d'autres organismes pour soutenir des individus ou des groupes, généralement pour des besoins spécifiques tels que l'aide sociale, le logement ou la famille.",
    "fiscalité": "La fiscalité désigne l'ensemble des règles et des lois relatives à l'imposition des revenus, des biens et des transactions, ainsi que le système de collecte des impôts par l'État et les collectivités.",
    "chômage": "Le chômage est la situation où des personnes en âge de travailler sont sans emploi et en recherchent activement, souvent mesurée par le taux de chômage dans une économie.",
    "crise": "Une crise est un événement ou une période de perturbation majeure qui affecte l'économie, la société ou la politique, entraînant des conséquences négatives, telles qu'une récession économique, des conflits ou des instabilités.",
    "imposition": "L'imposition est le processus par lequel l'État ou une autorité fiscale prélève des taxes ou des impôts sur les revenus, les biens ou les transactions des individus et des entreprises pour financer ses dépenses publiques.",
    "comptabilité": "La comptabilité est un système qui enregistre, classifie et résume les transactions financières d'une entreprise ou d'une organisation, permettant ainsi de suivre sa situation financière et d'élaborer des rapports",
    "cryptomonnaie": "Les cryptomonnaies sont des monnaies numériques qui utilisent la cryptographie pour sécuriser les transactions, contrôler la création de nouvelles unités et vérifier le transfert d'actifs, souvent basées sur la technologie de la blockchain.",
    "investissement": "L'investissement est l'acte de placer des ressources financières dans un actif, une entreprise ou un projet dans l'espoir de générer un rendement ou une plus-value sur le long terme.",
    "assurance": "L'assurance est un contrat par lequel un assureur s'engage à indemniser un assuré en cas de survenance d'un événement spécifique, en échange d'une prime régulière, offrant ainsi une protection financière contre divers risques.",
    "retraite": "La retraite est la période de la vie où une personne cesse de travailler, généralement après avoir atteint un certain âge, et reçoit des prestations financières, souvent sous forme de pensions, en fonction de ses cotisations et de ses années de travail.",
    "concurrence": "La concurrence est la situation dans laquelle plusieurs entreprises ou individus offrent des produits ou services similaires sur un marché, incitant à la rivalité pour attirer les consommateurs, ce qui peut conduire à une amélioration de la qualité et à une réduction des prix.",
    "oligopsone": "L'oligopsonie est une situation de marché où un petit nombre d'acheteurs domine l'achat d'un produit ou d'un service, ce qui leur confère un pouvoir de négociation important sur les prix et les conditions d'achat.",
    "oligopole": "L'oligopole est une structure de marché où un petit nombre d'entreprises contrôlent la majorité des ventes d'un produit ou d'un service, ce qui leur permet d'influencer les prix et de se surveiller mutuellement dans leurs décisions commerciales.",
    "batx": "BATX est un acronyme désignant les quatre grandes entreprises technologiques chinoises : Baidu, Alibaba, Tencent et Xiaomi. Ces entreprises jouent un rôle majeur dans l'économie numérique en Chine et sont connues pour leurs innovations et leur influence sur le marché technologique mondial.",
    "dette": "Ensemble des emprunts contractés par un État.",
    "pib": "Valeur totale des biens et services produits dans un pays sur une période donnée.",
    "amortissement": "Répartition d'un coût sur la durée de vie d'un actif.",
    "dividende": "Part des bénéfices distribuée aux actionnaires d'une entreprise.",
    "liquidité": "Capacité d'une entreprise à couvrir ses obligations à court terme.",
    "budget": "Prévision des revenus et dépenses sur une période donnée.",
    "rendement": "Ratio mesurant les gains ou les pertes sur un investissement.",
    "bourse": "Marché où s'échangent des actions et autres titres financiers.",
    "créance": "Droit de recevoir un paiement d'un débiteur.",
    "fusion": "Union de deux entreprises pour former une nouvelle entité.",
    "acquisition": "Achat d'une entreprise par une autre.",
    "bénéfice": "Excédent des revenus sur les dépenses d'une entreprise.",
    "monopole": "Situation où une seule entreprise domine un marché.",
    "filiale": "Société contrôlée par une autre société.",
    "prime": "Somme supplémentaire versée en plus d'un revenu ou d'un salaire.",
    "caution": "Garantie (financière) fournie par une personne pour s'assurer qu'une autre personne respectera ses obligations",
    "rtt": "dispositif qui permet aux employés de bénéficier de jours de repos supplémentaires par rapport à une durée de travail normale, souvent en échange d'un temps de travail hebdomadaire réduit.",
    "mutuelle": "organisation qui propose des services de santé complémentaires à l'assurance maladie",
    "devise": "unité monétaire acceptée par un pays étrange (ex : Euro, Dollar)",
    "héritage": "processus par lequel les biens, les droits et les obligations d'une personne décédée sont transmis à ses héritiers",
    "liquidation": "processus de clôture d'une entreprise ou d'une société, où ses actifs (biens et ressources) sont vendus pour rembourser ses dettes.",
    "quotas": "limite ou un seuil fixé pour une certaine quantité de quelque chose.",
    "faillite": "situation où une entreprise ou une personne ne peut plus payer ses dettes.",
    "hypothèque": "prêt garanti par un bien immobilier",
    "plainte": "déclaration officielle faite par une personne pour signaler un acte illégal ou un préjudice qu'elle a subi",
    "testament": "document écrit dans lequel une personne indique comment elle souhaite que ses biens et ses affaires soient répartis après sa mort",
    "sénat": "Institution qui joue un rôle important dans la création des lois et la représentation des régions ou des États",
    "entreprise": "organisation qui produit des biens ou offre des services dans le but de réaliser un profit.",
    "microentreprise": "un statut qui permet à une personne de créer et gérer facilement sa propre entreprise avec des démarches simplifiées et des limites de chiffre d'affaires.",
    "cac40": "indice boursier qui représente les 40 plus grandes entreprises cotées à la Bourse de Paris",
    "gafam": "les cinq grandes entreprises technologiques américaines : Google, Apple, Facebook (Meta), Amazon et Microsoft",
    "quotient": "Mécanisme utilisé pour calculer l'impôt sur le revenu, en fonction du nombre de personnes dans le foyer.",
    "assurance-vie": "Contrat permettant de constituer une épargne tout en assurant un capital en cas de décès.",
    "acompte": "Somme versée à l'avance pour garantir un achat ou un service.",
    "intérêt": "Somme payée ou reçue en contrepartie d'un prêt ou d'un investissement.",
    "capitalisme": "Le capitalisme est un système économique caractérisé par la propriété privée des moyens de production, la séparation du capital et du travail, et la régulation marchande.",
    "communisme": "Le communisme est initialement un ensemble de doctrines politiques, issues du socialisme et, pour la plupart, du marxisme, s'opposant au capitalisme et visant à l'instauration d'une société sans classes.",
};